[package]
name = "rorth"
version = "1.0.0"
edition = "2021"
authors = ["Allstreamer"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]


[dependencies]
thiserror = "1.0.30"
clap = { version = "3.1.5", features = ["derive"] }